# Generated by Django 5.1.4 on 2025-02-20 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarding',
            name='services',
            field=models.ManyToManyField(related_name='boardings', to='main.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='boarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_set', to='main.boarding', verbose_name='Передержка'),
        ),
    ]
