# Generated by Django 4.2.7 on 2025-05-23 03:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_update_user_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='animals',
        ),
        migrations.CreateModel(
            name='BookingAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_notes', models.TextField(blank=True, verbose_name='Особые заметки')),
                ('special_diet', models.CharField(blank=True, max_length=255, verbose_name='Особая диета')),
                ('medications', models.TextField(blank=True, verbose_name='Медикаменты')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.animal', verbose_name='Животное')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Животное в бронировании',
                'verbose_name_plural': 'Животные в бронировании',
                'unique_together': {('booking', 'animal')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='animals',
            field=models.ManyToManyField(related_name='bookings', through='main.BookingAnimal', to='main.animal', verbose_name='Животные'),
        ),
    ]
