# Generated by Django 4.2.7 on 2025-05-23 04:47

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_animal_is_available_review_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=main.models.animal_photo_path, verbose_name='Фотография животного'),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to=main.models.booking_document_path, verbose_name='Дополнительные документы'),
        ),
        migrations.AddField(
            model_name='booking',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.booking_document_path, verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to=main.models.booking_document_path, verbose_name='Чек об оплате'),
        ),
        migrations.AddField(
            model_name='dogsitter',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to=main.models.dogsitter_document_path, verbose_name='Сертификат о квалификации'),
        ),
        migrations.AddField(
            model_name='dogsitter',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to=main.models.dogsitter_document_path, verbose_name='Медицинская справка'),
        ),
        migrations.AddField(
            model_name='dogsitter',
            name='passport_scan',
            field=models.FileField(blank=True, null=True, upload_to=main.models.dogsitter_document_path, verbose_name='Скан паспорта'),
        ),
    ]
