# Generated by Django 4.2.7 on 2025-05-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_animal_photo_booking_additional_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogsitter',
            name='social_media_links',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылки на соцсети'),
        ),
        migrations.AddField(
            model_name='dogsitter',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Личный сайт'),
        ),
    ]
