# Generated by Django 4.2.7 on 2025-06-03 18:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dogsitter_social_media_links_dogsitter_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogsitter',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=main.models.dogsitter_document_path, verbose_name='Фотография догситтера'),
        ),
    ]
