# Generated by Django 4.2.7 on 2025-06-15 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_dogsitter_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogsitter',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dogsitter',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=main.models.dogsitter_document_path, verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='dogsitter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dogsitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
