# Generated by Django 4.2.9 on 2025-06-23 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_review_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MZexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('exam_date', models.DateTimeField(verbose_name='Дата проведения экзамена')),
                ('task_image', models.ImageField(blank=True, null=True, upload_to='exams/', verbose_name='Изображение задания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('students', models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Студенты')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['-exam_date'],
            },
        ),
    ]
